# Generated by Django 5.0.7 on 2024-07-26 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0006_remove_producto_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
