# Generated by Django 5.0.7 on 2024-07-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0007_alter_categoria_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria_id',
            new_name='categoria',
        ),
    ]
