# Generated by Django 5.0.7 on 2024-07-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0008_rename_categoria_id_producto_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
