# Generated by Django 5.0.7 on 2024-07-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0009_alter_categoria_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precio',
            name='cantidad',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_total',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='precio',
            name='precio_uni',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
