# Generated by Django 5.0.7 on 2024-07-26 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0010_alter_precio_cantidad_alter_precio_precio_total_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
